apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.app.name}}
spec:
  replicas: {{.Values.app.replicas}}
  selector:
    matchLabels:
      app: {{.Values.app.name}}
  template:
    metadata:
      labels:
        app: {{.Values.app.name}}
    spec:
      restartPolicy: Always
      containers:
        - name: {{.Values.app.name}}
          image: {{ .Values.app.image }}
          ports:
            - containerPort: {{.Values.app.port}}
          env:
            - name: MYSQL_HOST
              value: {{ .Values.database.name }}
            - name: MYSQL_PORT
              value: "{{.Values.database.port}}"
            - name: MYSQL_USER
              value: {{ .Values.app.username }}
            - name: MYSQL_PASS
              value: "{{.Values.app.password}}"
          resources:
            limits:
              cpu: 500m