app:
  name: goapp-server
  image: omarmokhtar99/go-docker-app:latest
  replicas: 2
  port: 9090
  username: root
  password: 123456789

database:
  name: goapp-db
  image: mysql:8.0
  port: 3306
  rootPassword: 123456789
